name: autocomplete_textfield
description: A simple and versatile autocomplete text field for flutter, supporting multiple datatypes.
version: 1.7.3
homepage: https://github.com/felixlucien/flutter-autocomplete-textfield

environment:
    sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fake_async: ^1.3.3
  async: ^2.13.0
  leak_tracker: ^10.0.9
  material_color_utilities: ^0.12.0
  vm_service: ^15.0.0

dependency_overrides:
  material_color_utilities: ^0.12.0

#dev_dependencies:
#  flutter_test:
#    sdk: flutter